### ISSUE TITLE
RuntimeError: /pytorch/torch/csrc/jit/fuser/cuda/fused_kernel.cpp:196: NVRTC_ERROR unknown

### ISSUE THREAD

**Issue by HTL2018** [weiaicunzai/pytorch-cifar100#11]
When I use googlenet ,vgg, it worked normally.  
But when I use resnet ,the error occured:  
`RuntimeError: /pytorch/torch/csrc/jit/fuser/cuda/fused_kernel.cpp:196: NVRTC_ERROR unknown`

**Comment by weiaicunzai** [comment]
I've tested  resnett18 - resnet152 on google colab,  didn't encounter the bug you mentioned,  so there is a highly change that something is wrong with your environment configuration.
