### ISSUE TITLE
GPU利用率

### ISSUE THREAD

**Issue by Clannad000000** [weiaicunzai/pytorch-cifar100#14]
博主您好，请问我在训练时GPU利用率只能维持在10%左右，对应的batch_size是64，num_workers是8。请问有没有什么办法提高利用率呢？

**Comment by chituma110** [comment]
dali 出奇迹。

**Comment by Clannad000000** [comment]
> dali 出奇迹。

怎么个dali法？

**Comment by weiaicunzai** [comment]
> > dali 出奇迹。
> 
> 怎么个dali法？

A nvidia  libaray preloads data to gpu to accelerate training process: https://docs.nvidia.com/deeplearning/dali/user-guide/docs/.

But I think you could just simply use larger  batch_size to increase the GPU memory usage
