### ISSUE TITLE
Is this a mistake in senet for fair comparison?

### ISSUE THREAD

**Issue by vinthony** [weiaicunzai/pytorch-cifar100#18]
I notice that the stage4 of other instance of `ResNet` is 512 while the `SENet` is 516,
Is this a bug?
SENet:
https://github.com/weiaicunzai/pytorch-cifar100/blob/1fe2ec40dc05cd81fee6ab23de09b99fdb0d282f/models/senet.py#L126
ResNet:
https://github.com/weiaicunzai/pytorch-cifar100/blob/1fe2ec40dc05cd81fee6ab23de09b99fdb0d282f/models/resnet.py#L96
ReXsNet:
https://github.com/weiaicunzai/pytorch-cifar100/blob/1fe2ec40dc05cd81fee6ab23de09b99fdb0d282f/models/resnext.py#L80

**Comment by weiaicunzai** [comment]
Yes, it is a bug, already fixed, thanks
