### ISSUE TITLE
accuracy of shufflenet v2

### ISSUE THREAD

**Issue by doublejtoh** [weiaicunzai/pytorch-cifar100#3]
I tried to train shufflenet v2 with your scipt with default hyper parameters you set. 
It should yield  69.51 % of best test accuracy but i got best test accuracy 61.68%. So what hyper parameters did you use??

**Comment by weiaicunzai** [comment]
probably because of the warm up training phase, you could try to set warm up training phase at 1 or 2.Sorry I cant remember the specific number I´ve used.
