### ISSUE TITLE
The accuracy of vgg16-bn and vgg19_bn

### ISSUE THREAD

**Issue by Ameliapeng** [weiaicunzai/pytorch-cifar100#33]

**Comment by Ameliapeng** [comment]
想问一下，我直接用的原来的代码但是精确度一直训不上去，vgg16和vgg19一直都在68左右是怎么回事呢？

**Comment by weiaicunzai** [comment]
> 想问一下，我直接用的原来的代码但是精确度一直训不上去，vgg16和vgg19一直都在68左右是怎么回事呢？

现在呢

**Comment by kingrain213** [comment]
想请问一下我也一直训不上去，准确率不到20%，是因为参数没有初始化的缘故还是什么呢？

**Comment by kingrain213** [comment]
> > 想问一下，我直接用的原来的代码但是精确度一直训不上去，vgg16和vgg19一直都在68左右是怎么回事呢？
> 
> 现在呢

想请问一下我也一直训不上去，准确率不到20%，是因为参数没有初始化的缘故还是什么呢？
