### ISSUE TITLE
Multiple GPUs

### ISSUE THREAD

**Issue by JanineCHEN** [weiaicunzai/pytorch-cifar100#37]
Great thanks for sharing the codes!

One question, does the training support multiple GPUs? Kindly correct if I am mistaken, but as far as I can tell, the codes only support single GPU now?

**Comment by weiaicunzai** [comment]
My code  doesn't support multi GPU, sry, I think you could slightly modify the code to support multi gpu training:
example:
```
net = nn.DataParallel(net, device_ids=args.gpus)
```
The pytorch ```nn.DataParallel``` could easily make your code to support multi GPU training
docs:   https://pytorch.org/docs/stable/generated/torch.nn.DataParallel.html

**Comment by JanineCHEN** [comment]
> My code doesn't support multi GPU, sry, I think you could slightly modify the code to support multi gpu training:
> example:
> 
> ```
> net = nn.DataParallel(net, device_ids=args.gpus)
> ```
> 
> The pytorch `nn.DataParallel` could easily make your code to support multi GPU training
> docs: https://pytorch.org/docs/stable/generated/torch.nn.DataParallel.html

Thank you! I have tried and it works.
