### ISSUE TITLE
print(torch.cuda.memory_summary(), end='')

### ISSUE THREAD

**Issue by xiaoxiannvlgy** [weiaicunzai/pytorch-cifar100#39]
AttributeError: module torch.cuda has no attribute memory_summary
![image](https://user-images.githubusercontent.com/59329144/96966518-83e75c00-1540-11eb-8814-aca81ea4003f.png)

What the meaning of "torch.cuda.memory_summary()"  ??
What does the author want to express in this sentence  “print(torch.cuda.memory_summary(), end='')”  
train.py  line 100

**Comment by weiaicunzai** [comment]
Which pytorch version are you using ?I am using google colab to train my model which is currently pytorch 1.6
