### ISSUE TITLE
About the nums of filters of the preactreanet.py

### ISSUE THREAD

**Issue by SWHL** [weiaicunzai/pytorch-cifar100#4]
In the 86 line of the 'pytorch-cifar100/models/preactresnet.py' file, as the under shows:
https://github.com/weiaicunzai/pytorch-cifar100/blob/1f0273398f79d3ea5cbea2f450b64258c44f6415/models/preactresnet.py#L86 
I think the 156 filters, here, should be the 512.

**Comment by weiaicunzai** [comment]
Yes, you are right, thanks for pointing out
