### ISSUE TITLE
我想知道为什么我跑了很多次 但是结果都远好于作者给出的表格里的结果 是不是我测试错了 resnet50

### ISSUE THREAD

**Issue by a957815154** [weiaicunzai/pytorch-cifar100#45]
![image](https://user-images.githubusercontent.com/32867276/104405280-913c4180-5597-11eb-967a-457f436ad6fa.png)
![image](https://user-images.githubusercontent.com/32867276/104405306-9c8f6d00-5597-11eb-8fa1-1b55822fffcb.png)
![image](https://user-images.githubusercontent.com/32867276/104405332-ae711000-5597-11eb-8824-ae00b4c57634.png)

**Comment by ygtxr1997** [comment]
作者的 topk 计算貌似有问题，我改成了 pytorch 官方给的 imagenet 测试的代码，计算就对了

**Comment by a957815154** [comment]
能给我修改的关键处的代码截图吗&nbsp;谢谢了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "weiaicunzai/pytorch-cifar100"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月12日(星期天) 中午12:31
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [weiaicunzai/pytorch-cifar100] 我想知道为什么我跑了很多次 但是结果都远好于作者给出的表格里的结果 是不是我测试错了 resnet50 (#45)





 
作者的 topk 计算貌似有问题，我改成了 pytorch 官方给的 imagenet 测试的代码，计算就对了
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
