### ISSUE TITLE
boolean type can be accepted rightly as an argument in train.py 

### ISSUE THREAD

**Issue by lionkunonly** [weiaicunzai/pytorch-cifar100#9]
In the train.py, the argument **gpu** and **s** will be accepted as boolean. However, in normal ways, if you input the command like the following:
python train.py -gpu False -s False

you will find the **arg.gpu** and **arg.s** are True. It means that the arguments gpu and s do not accept the input rightly.

**Comment by lucgiffon** [comment]
Yes this is not how one should handle boolean arguments with `argparse`. You can use instead:

    parser.add_argument('-no-gpu', action='store_false', default=True, help='use gpu or not')
    parser.add_argument('-no-s', action='store_false', default=True, help='whether shuffle the dataset')

and modify the rest of the code accordingly to match the new arguments names.

**Comment by weiaicunzai** [comment]
Thanks guys,  already fixed that.
